version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: elearning_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: elearning123
      MYSQL_DATABASE: elearning_db
      MYSQL_USER: elearning_user
      MYSQL_PASSWORD: elearning_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - elearning_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: elearning_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: elearning123
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - elearning_network

volumes:
  mysql_data:

networks:
  elearning_network:
    driver: bridge
